### ISSUE TITLE
Problems in script.js 

### ISSUE THREAD

**Issue by fgadaleta** [fgadaleta/amethix-webpage#28]
If you log when script is active and you scroll and animations start, there is this issue I think it's responsible of not animating stuff correctly sometimes.
Mind looking into that? 

```
Uncaught TypeError: $(...).slick is not a function
    <anonymous> http://localhost:4000/assets/js/script.js:73
    <anonymous> http://localhost:4000/assets/js/script.js:378
script.js:73:22
```

**Comment by ark622** [comment]
fixed
